### ISSUE TITLE
Preparing a research document

### ISSUE THREAD

**Issue by akarakoc** [akarakoc/SWE574#5]
Research document  will be prepared about 
**W3C Activity Stream
W3C Web Annotation Data Model
Wikidata**

**Comment by akarakoc** [comment]
I prepared my [document ](https://github.com/akarakoc/SWE574/wiki/Research-on-Web-Annotation-Model) please review it if you have any question let me know!

**Comment by tutkubayri** [comment]
I completed [Wikidata Research](http://localhost:8889/?token=712cd32f38522c3cfb3e375dcf6af008aa4dbad8660c850d). Check it out and let me know if there is something you want to ask.

**Comment by mateskarayol** [comment]
I prepare some useful introductory information about Activity Streams. For more detailed information, useful documentation resources also added on wikipage. Document is ready for now, it will be enhanced in time.

**Comment by akarakoc** [comment]
Thank you friends all seems good, I'm closing the issue
